name: phamijam
description: "PhamiJam - Music player for Phamishan & friends"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    audio_video_progress_bar: ^2.0.3
    provider: ^6.1.5
    http: ^1.4.0
    path_provider: ^2.1.5
    permission_handler: ^12.0.0+1
    just_audio: ^0.10.2
    just_audio_windows: ^0.2.2
    audio_metadata_reader: ^1.4.1
    marquee: ^2.2.3
    shared_preferences: ^2.5.3
    flutter_secure_storage: ^9.2.4
    file_picker: ^6.1.1
    youtube_explode_dart: ^2.5.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
    fonts:
        - family: Lexend
          fonts:
              - asset: assets/fonts/Lexend-Regular.ttf
